Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjectFirst.Controllers
{
    public class AdminController : Controller
    {
        // GET: Admin
        public ActionResult Dashboard()
        {
            return View();
        }
    }
}

Controllers/CategoryController.cs
using ProjectFirst.Models;
using ProjectFirst.Models.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjectFirst.Controllers
{
    public class CategoryController : Controller
    {
        // GET: Category
        public ActionResult ManageCategory()
        {
            return View();
        }
        public JsonResult GetData()
        {
            using (ProjectEntities db = new ProjectEntities())
            {
                db.Configuration.LazyLoadingEnabled = false;
                List<CategoryViewModel> lst = new List<CategoryViewModel>();
                var catList = db.tblCategories.ToList();
                foreach (var item in catList)
                {
                    lst.Add(new CategoryViewModel() { CategoryId = item.CategoryId, CategoryName = item.CategoryName });
                }
                return Json(new { data = lst }, JsonRequestBehavior.AllowGet);
            }
        }


        [HttpGet]
        public ActionResult AddOrEdit(int id = 0)
        {
            if (id == 0)
            {
                using (ProjectEntities db = new ProjectEntities())
                {
                    ViewBag.Action = "New Category";
                    return View(new CategoryViewModel());
                }
            }
            else
            {
                using (ProjectEntities db = new ProjectEntities())
                {
                    CategoryViewModel sub = new CategoryViewModel();
                    var menu = db.tblCategories.Where(x => x.CategoryId == id).FirstOrDefault();
                    sub.CategoryId = menu.CategoryId;
                    sub.CategoryName = menu.CategoryName;
                    ViewBag.Action = "Edit Category";
                    return View(sub);
                }
            }
        }
        [HttpPost]
        public ActionResult AddOrEdit(CategoryViewModel sm)
        {
            using (ProjectEntities db = new ProjectEntities())
            {
                if (sm.CategoryId == 0)
                {
                    tblCategory tb = new tblCategory();
                    tb.CategoryName = sm.CategoryName;
                    db.tblCategories.Add(tb);
                    db.SaveChanges();
                    return Json(new { success = true, message = "Saved Successfully" }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    tblCategory tbm = db.tblCategories.Where(m => m.CategoryId == sm.CategoryId).FirstOrDefault();
                    tbm.CategoryName = sm.CategoryName;
                    db.SaveChanges();
                    return Json(new { success = true, message = "Updated Successfully" }, JsonRequestBehavior.AllowGet);
                }
            }


        }
        [HttpPost]
        public ActionResult Delete(int id)
        {
            using (ProjectEntities db = new ProjectEntities())
            {
                tblCategory sm = db.tblCategories.Where(x => x.CategoryId == id).FirstOrDefault();
                db.tblCategories.Remove(sm);
                db.SaveChanges();
                return Json(new { success = true, message = "Deleted Successfully" }, JsonRequestBehavior.AllowGet);
            }
        }

    }
}

Controllers/ProductController.cs
using ProjectFirst.Models;
using ProjectFirst.Models.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjectFirst.Controllers
{
    public class ProductController : Controller
    {
        // GET: Product
        public ActionResult ManageProduct()
        {
            return View();
        }
        public JsonResult GetData()
        {
            using (ProjectEntities db = new ProjectEntities())
            {
                db.Configuration.LazyLoadingEnabled = false;
                List<ProductViewModel> lstitem = new List<ProductViewModel>();
                var lst = db.tblProducts.Include("tblCategory").ToList();
                foreach (var item in lst)
                {
                    lstitem.Add(new ProductViewModel() { ProductId = item.ProductId, CategoryName = item.tblCategory.CategoryName, ProductName = item.ProductName, UnitPrice = item.UnitPrice, SellingPrice = item.SellingPrice, Photo = item.Photo });
                }
                return Json(new { data = lstitem }, JsonRequestBehavior.AllowGet);
            }
        }
        [HttpGet]
        public ActionResult AddOrEdit(int id = 0)
        {
            if (id == 0)
            {
                using (ProjectEntities db = new ProjectEntities())
                {
                    ViewBag.Categories = db.tblCategories.ToList();
                    ViewBag.Action = "Create New Product";
                    return View(new ProductViewModel());
                }
            }
            else
            {
                using (ProjectEntities db = new ProjectEntities())
                {
                    ViewBag.Action = "Edit Product";
                    ViewBag.Categories = db.tblCategories.ToList();
                    tblProduct item = db.tblProducts.Where(i => i.ProductId == id).FirstOrDefault();
                    ProductViewModel itemvm = new ProductViewModel();
                    itemvm.ProductId = item.ProductId;
                    itemvm.CategoryId = Convert.ToInt32(item.CategoryId);
                    itemvm.ProductName = item.ProductName;
                    itemvm.UnitPrice = item.UnitPrice;
                    itemvm.SellingPrice = item.SellingPrice;
                    itemvm.Description = item.Description;
                    itemvm.Photo = item.Photo;
                    itemvm.IsSpecial = item.IsSpecial;

                    return View(itemvm);
                }
            }
        }

        [HttpPost]

        public ActionResult AddOrEdit(ProductViewModel ivm)
        {
            using (ProjectEntities db = new ProjectEntities())
            {
                if (ivm.ProductId == 0)
                {
                    tblProduct itm = new tblProduct();

                    itm.CategoryId = Convert.ToInt32(ivm.CategoryId);
                    itm.ProductName = ivm.ProductName;
                    itm.UnitPrice = ivm.UnitPrice;
                    itm.SellingPrice = ivm.SellingPrice;
                    itm.Description = ivm.Description;
                    itm.IsSpecial = ivm.IsSpecial;

                    HttpPostedFileBase fup = Request.Files["Photo"];
                    if (fup != null)
                    {
                        if (fup.FileName != "")
                        {
                            fup.SaveAs(Server.MapPath("~/ProductImages/" + fup.FileName));
                            itm.Photo = fup.FileName;
                        }
                    }

                    db.tblProducts.Add(itm);
                    db.SaveChanges();
                    ViewBag.Message = "Created Successfully";
                }
                else
                {
                    tblProduct itm = db.tblProducts.Where(i => i.ProductId == ivm.ProductId).FirstOrDefault();
                    itm.CategoryId = Convert.ToInt32(ivm.CategoryId);
                    itm.ProductName = ivm.ProductName;
                    itm.UnitPrice = ivm.UnitPrice;
                    itm.SellingPrice = ivm.SellingPrice;
                    itm.Description = ivm.Description;
                    itm.IsSpecial = ivm.IsSpecial;
                    HttpPostedFileBase fup = Request.Files["SmallImage"];
                    if (fup != null)
                    {
                        if (fup.FileName != "")
                        {
                            fup.SaveAs(Server.MapPath("~/ProductImages/" + fup.FileName));
                            itm.Photo = fup.FileName;
                        }
                    }



                    db.SaveChanges();
                    ViewBag.Message = "Updated Successfully";

                }
                ViewBag.Categories = db.tblCategories.ToList();
                return View(new ProductViewModel());

            }


        }

        [HttpPost]

        public ActionResult Delete(int id)
        {
            using (ProjectEntities db = new ProjectEntities())
            {
                tblProduct sm = db.tblProducts.Where(x => x.ProductId == id).FirstOrDefault();
                db.tblProducts.Remove(sm);
                db.SaveChanges();
                return Json(new { success = true, message = "Deleted Successfully" }, JsonRequestBehavior.AllowGet);
            }
        }

    }
}

Views/Shared/_Layout.cshtml
@using ProjectFirst.Models
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/css/font-awesome.min.css" rel="stylesheet">
    <link href="~/css/datepicker3.css" rel="stylesheet">
    <link href="~/css/styles.css" rel="stylesheet">
    <link href="~/css/jquery-ui.min.css" rel="stylesheet" />


    <!--Custom Font-->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
</head>
<body>


    <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#sidebar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#"><span>Lumino</span>Admin</a>
                <ul class="nav navbar-top-links navbar-right">

                    <li class="dropdown">
                        <a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">
                            <em class="fa fa-user-circle"></em>
                        </a>
                        <ul class="dropdown-menu dropdown-alerts">
                            <li>
                                <a href="@Url.Action("ChangePassword","Account")">
                                    <div>
                                        <em class="fa fa-key"></em> Change Password

                                    </div>
                                </a>
                            </li>
                            <li class="divider"></li>
                            <li>
                                <a href="@Url.Action("Logout","Account")">
                                    <div>
                                        <em class="fa fa-heart"></em> Logout

                                    </div>
                                </a>
                            </li>

                            <li class="divider"></li>
                            <li>
                                <a href="@Url.Action("Index","Home")">
                                    <div>
                                        <em class="fa fa-home"></em> Back To Page

                                    </div>
                                </a>
                            </li>
                            <li class="divider"></li>

                        </ul>
                    </li>
                </ul>
            </div>
        </div><!-- /.container-fluid -->
    </nav>
    <div id="sidebar-collapse" class="col-sm-3 col-lg-2 sidebar">
        <div class="profile-sidebar">
            <div class="profile-userpic">
                <img src="~/ProductImages/trek.jpg" class="img-responsive" alt="">
            </div>
            <div class="profile-usertitle">
                <div class="profile-usertitle-name">@User.Identity.Name</div>
                <div class="profile-usertitle-status"><span class="indicator label-success"></span>Online</div>
            </div>
            <div class="clear"></div>
        </div>
        <div class="divider"></div>
        <form role="search">
            <div class="form-group">
                <input type="text" class="form-control" placeholder="Search">
            </div>
        </form>
        <ul class="nav menu">
            <li class="active"><a href="@Url.Action("Dashboard","Admin")"><em class="fa fa-dashboard">&nbsp;</em> Dashboard</a></li>
            <li><a href="@Url.Action("ManageCategory","Category")"><em class="fa fa-calendar">&nbsp;</em> Manage Category</a></li>
            <li><a href="@Url.Action("ManageProduct","Product")"><em class="fa fa-bar-chart">&nbsp;</em> Manage Product</a></li>

          
                <li><a href="#"><em class="fa fa-toggle-off">&nbsp;</em>Manage User</a></li>
            
            <li><a href="@Url.Action("ChangePassword","Account")"><em class="fa fa-clone">&nbsp;</em> Change Password</a></li>
            <li><a href="@Url.Action("Index","Home")"><em class="fa fa-home">&nbsp;</em> Back To Page </a></li>
            <li><a href="@Url.Action("Logout","Account")"><em class="fa fa-power-off">&nbsp;</em> Logout</a></li>

        </ul>
    </div><!--/.sidebar-->



    @RenderBody()



    <script src="~/js/jquery-1.11.1.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/chart.min.js"></script>
    <script src="~/js/chart-data.js"></script>
    <script src="~/js/easypiechart.js"></script>
    <script src="~/js/easypiechart-data.js"></script>
    <script src="~/js/bootstrap-datepicker.js"></script>
    <script src="~/js/custom.js"></script>
    <script src="~/js/jquery-ui-1.12.1.min.js"></script>
    <script src="~/js/jquery.validate.min.js"></script>
    <script src="~/js/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/js/notify.min.js"></script>
    <script>
        window.onload = function () {
            var chart1 = document.getElementById("line-chart").getContext("2d");
            window.myLine = new Chart(chart1).Line(lineChartData, {
                responsive: true,
                scaleLineColor: "rgba(0,0,0,.2)",
                scaleGridLineColor: "rgba(0,0,0,.05)",
                scaleFontColor: "#c5c7cc"
            });
        };
    </script>
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_LayoutUI.cshtml
@using ProjectFirst.Models
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <script type="application/x-javascript">
         addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false);
        function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!-- //for-mobile-apps -->

    <link href="~/rootcss/css/bootstrap.css" rel='stylesheet' type='text/css' />
    <!-- Custom Theme files -->
    <link href="~/rootcss/css/style.css" rel='stylesheet' type='text/css' />
    <!-- js -->
    <script src="~/rootcss/js/jquery-1.11.1.min.js"></script>
    <!-- //js -->
    <!-- start-smoth-scrolling -->
    <script type="text/javascript" src="js/move-top.js"></script>
    <script type="text/javascript" src="js/easing.js"></script>
    <script type="text/javascript">
        jQuery(document).ready(function ($) {
            $(".scroll").click(function (event) {
                event.preventDefault();
                $('html,body').animate({ scrollTop: $(this.hash).offset().top }, 1000);
            });
        });
    </script>
    <!-- start-smoth-scrolling -->
    <link href="~/rootcss/css/font-awesome.css" rel="stylesheet">
    <link href='//fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
    <link href='//fonts.googleapis.com/css?family=Noto+Sans:400,700' rel='stylesheet' type='text/css'>
    <!--- start-rate---->
    <script src="~/rootcss/js/jstarbox.js"></script>
    <link rel="stylesheet" href="~/rootcss/css/jstarbox.css" type="text/css" media="screen" charset="utf-8" />
    <script type="text/javascript">
        jQuery(function () {
            jQuery('.starbox').each(function () {
                var starbox = jQuery(this);
                starbox.starbox({
                    average: starbox.attr('data-start-value'),
                    changeable: starbox.hasClass('unchangeable') ? false : starbox.hasClass('clickonce') ? 'once' : true,
                    ghosting: starbox.hasClass('ghosting'),
                    autoUpdateAverage: starbox.hasClass('autoupdate'),
                    buttons: starbox.hasClass('smooth') ? false : starbox.attr('data-button-count') || 5,
                    stars: starbox.attr('data-star-count') || 5
                }).bind('starbox-value-changed', function (event, value) {
                    if (starbox.hasClass('random')) {
                        var val = Math.random();
                        starbox.next().text(' ' + val);
                        return val;
                    }
                })
            });
        });
    </script>
    <!---//End-rate---->
</head>
<body>

    <div class="header">

        <div class="container">

            <div class="logo">
                <h1><a href="index.html"><b>T<br>H<br>E</b>Butter<span>Bake & Cake</span></a></h1>
            </div>
            <div class="head-t">
                <ul class="card">

                    <li><a href="@Url.Action("Login","Account")"><i class="fa fa-user" aria-hidden="true"></i>Login</a></li>
                    <li><a href="#"><i class="fa fa-arrow-right" aria-hidden="true"></i>Register</a></li>
                    <li><a href="#"><i class="fa fa-file-text-o" aria-hidden="true"></i>WELCOME:@User.Identity.Name</a></li>

                </ul>
            </div>

            <div class="header-ri">
                <ul class="social-top">
                    <li><a href="#" class="icon facebook"><i class="fa fa-facebook" aria-hidden="true"></i><span></span></a></li>
                    <li><a href="#" class="icon twitter"><i class="fa fa-twitter" aria-hidden="true"></i><span></span></a></li>
                    <li><a href="#" class="icon pinterest"><i class="fa fa-pinterest-p" aria-hidden="true"></i><span></span></a></li>
                    <li><a href="#" class="icon dribbble"><i class="fa fa-dribbble" aria-hidden="true"></i><span></span></a></li>
                </ul>
            </div>


            <div class="nav-top">
                <nav class="navbar navbar-default">

                    <div class="navbar-header nav_2">
                        <button type="button" class="navbar-toggle collapsed navbar-toggle1" data-toggle="collapse" data-target="#bs-megadropdown-tabs">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>


                    </div>
                    <div class="collapse navbar-collapse" id="bs-megadropdown-tabs">
                        <ul class="nav navbar-nav ">
                            <li class=" active"><a href="@Url.Action("Index", "Home")" class="hyper "><span>Home</span></a></li>
                            @{
                                List<tblCategory> myMenu = MyMenu.GetMenus();

                                foreach (var item in myMenu)
                                {
                                    <li>
                                        <a href="@Url.Action("ProductList", "Home", new { id = item.CategoryId })" class="hyper">@item.CategoryName</a>
                                    </li>
                                }
                            }


                            <li><a href="#" class="hyper"> <span>Codes</span></a></li>
                            <li><a href="@Url.Action("Contact","Home")" class="hyper"><span>Contact Us</span></a></li>
                        </ul>
                    </div>
                </nav>
                <div class="cart">

                    <span class="fa fa-shopping-cart my-cart-icon"><span class="badge badge-notify my-cart-badge"></span></span>
                </div>
                <div class="clearfix"></div>
            </div>

        </div>
    </div>
    @RenderSection("banner", required: false)
    <!---->


    <script>window.jQuery || document.write('<script src="~/rootcss/js/vendor/jquery-1.11.1.min.js"><\/script>')</script>
    <script src="~/rootcss/js/jquery.vide.min.js"></script>


    @RenderBody()

    <!--footer-->
    <div class="footer">
        <div class="container">

            <div class="clearfix"></div>
            <div class="footer-bottom">
                <h2><a href="index.html"><b>T<br>H<br>E</b>Butter<span>Bake & Cake</span></a></h2>
                <p class="fo-para">Home made cake with love and care, we are newly opened and ready to serve at your doorstep according to your needs.</p>
                <ul class="social-fo">
                    <li><a href="https://www.facebook.com/BroadwayInfo/" class=" face"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>

                </ul>
                <div class=" address">
                    <div class="col-md-4 fo-grid1">
                        <p><i class="fa fa-home" aria-hidden="true"></i>Saurab Shrestha</p>
                    </div>
                    <div class="col-md-4 fo-grid1">
                        <p><i class="fa fa-phone" aria-hidden="true"></i>+977-9813508930</p>
                    </div>
                    <div class="col-md-4 fo-grid1">
                        <p><a href="mailto:info@example.com"><i class="fa fa-envelope-o" aria-hidden="true"></i>saurab.shrestha1010@gmail.com</a></p>
                    </div>
                    <div class="clearfix"></div>

                </div>
            </div>
            <div class="copy-right">
                <p> &copy; 2021 Far West. All Rights Reserved | Design by  <a href="#"> Saurab Shrestha</a></p>
            </div>
        </div>
    </div>
    <!-- //footer-->
    <!-- smooth scrolling -->
    <script type="text/javascript">
        $(document).ready(function () {
            /*
                var defaults = {
                containerID: 'toTop', // fading element id
                containerHoverID: 'toTopHover', // fading element hover id
                scrollSpeed: 1200,
                easingType: 'linear'
                };
            */
            $().UItoTop({ easingType: 'easeOutQuart' });
        });
    </script>
    <a href="#" id="toTop" style="display: block;"> <span id="toTopHover" style="opacity: 1;"> </span></a>
    <!-- //smooth scrolling -->
    <!-- for bootstrap working -->
    <script src="~/rootcss/js/bootstrap.js"></script>
    <!-- //for bootstrap working -->
    <!-- product -->

</body>
</html>